-- Prefect + Snowflake Quickstart: Database Setup
-- Run this in a Snowsight SQL Worksheet

CREATE DATABASE IF NOT EXISTS PREFECT_QUICKSTART;
USE DATABASE PREFECT_QUICKSTART;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

CREATE WAREHOUSE IF NOT EXISTS PREFECT_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE SCHEMA RAW;
CREATE OR REPLACE TABLE PULL_REQUESTS (
    PR_NUMBER      NUMBER,
    REPO           VARCHAR,
    TITLE          VARCHAR,
    AUTHOR         VARCHAR,
    DIFF_CONTENT   VARCHAR(16777216),
    FILES_CHANGED  NUMBER,
    ADDITIONS      NUMBER,
    DELETIONS      NUMBER,
    CREATED_AT     TIMESTAMP_NTZ,
    LOADED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

USE SCHEMA ANALYTICS;
CREATE OR REPLACE TABLE PR_ASSESSMENTS (
    PR_NUMBER       NUMBER,
    REPO            VARCHAR,
    RISK_LEVEL      VARCHAR(20),
    SUMMARY         VARCHAR(16777216),
    DECISION        VARCHAR(20),
    REVIEWER        VARCHAR,
    REVIEWER_NOTES  VARCHAR(16777216),
    ASSESSED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PR_HISTORY (
    PR_NUMBER      NUMBER,
    REPO           VARCHAR,
    AUTHOR         VARCHAR,
    RISK_LEVEL     VARCHAR(20),
    HAD_INCIDENT   BOOLEAN,
    MERGED_AT      TIMESTAMP_NTZ
);

INSERT INTO PR_HISTORY VALUES
(101, 'acme/data-platform', 'alice', 'low', FALSE, '2025-12-01 10:00:00'),
(102, 'acme/data-platform', 'bob', 'high', TRUE, '2025-12-15 14:30:00'),
(103, 'acme/data-platform', 'alice', 'medium', FALSE, '2026-01-10 09:00:00'),
(104, 'acme/data-platform', 'charlie', 'low', FALSE, '2026-02-01 11:00:00'),
(105, 'acme/data-platform', 'bob', 'medium', TRUE, '2026-03-01 16:00:00');

-- Verify Cortex AI
SELECT SNOWFLAKE.CORTEX.COMPLETE('mistral-large2', 'Say hello') AS test;
